name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: shrt
            asset_name: shrt-linux-x86_64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: shrt.exe
            asset_name: shrt-windows-x86_64.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: shrt
            asset_name: shrt-macos-x86_64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: shrt
            asset_name: shrt-macos-arm64

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        with:
          files: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}